### ISSUE TITLE
按照给的命令执行访问不了web服务

### ISSUE THREAD

**Issue by 2477231995** [yqcs/prismx#12]
![image](https://github.com/user-attachments/assets/79c44206-fff3-48b9-8b28-bfcd4092d579)
![image](https://github.com/user-attachments/assets/079d4d62-815a-495d-b5e2-e24029aa4a5b)

**Comment by 2477231995** [comment]
我执行了这些命令，更换端口启动也访问不了web服务
![image](https://github.com/user-attachments/assets/e9df032a-1916-47ee-90e7-9ab5a91b123f)

**Comment by yqcs** [comment]
请检查防火墙与云安全防护是否放行。如果不放心，可以新开个端口，执行一下curl https://127.0.0.1

**Comment by 2477231995** [comment]
感谢师傅，云开安全组忘开防火墙端口了
