### ISSUE TITLE
平台存在 URL 重定向漏洞

### ISSUE THREAD

**Issue by examenes3** [yqcs/prismx#15]
修改 redirect 参数为任意链接
![image](https://github.com/user-attachments/assets/fefc7266-c315-4280-aebd-5da94d15e4b1)
登录成功后会直接跳转到相应链接
![image](https://github.com/user-attachments/assets/2843c87f-6bf8-4264-9ae1-c5b567e5252d)

**Comment by yqcs** [comment]
谢谢，内部已知，无特殊需求暂无整改安排
