### ISSUE TITLE
Linux Web端启动报错 Segmentation fault (core dumped)，使用默认端口或者-port参数指定端口均无法启动。

### ISSUE THREAD

**Issue by muyuanlove** [yqcs/prismx#3]
环境:
纯净Ubuntu22.04 x64 香港云服务器

命令:
wget https://github.com/yqcs/prismx/releases/download/1.0.20/prismx.zip
unzip prismx.zip
cd prismx/
chmod 777 prismx_linux_amd64
./prismx_linux_amd64
./prismx_linux_amd64 -port 40000

疑问:
我看了那两个lssues，你这个新年快乐发个不能启动的虚空包助兴？

**Comment by yqcs** [comment]
换个arm的试试 另，另外两个issues是没发布之前就有了
