### ISSUE TITLE
wtf，什么情况

### ISSUE THREAD

**Issue by hmyl1** [yqcs/prismx#5]

**Comment by hmyl1** [comment]
![图片](https://github.com/yqcs/prismx/assets/139748405/7047fc74-e54b-499f-9750-3f3462c0dd72)
![图片](https://github.com/yqcs/prismx/assets/139748405/71cf5617-13c4-4c07-8594-4124061d831c)

**Comment by D2550** [comment]
pls use https

**Comment by yqcs** [comment]
pls use https
